### DISCUSSION TITLE
Creating a relation record when it does not exist

### DISCUSSION THREAD

**Discussion by shahzaib78631** [mnfst/llm-gateway#264] [Feature request]
Hello Manifest Team, I would like to request a feature for creating a record in a relation when it does not exist or updating when it does exist when creating/updating an entity. Or maybe any way to extend the API for such operations.

Example:

```
Items:
    properties:
      - name
      - { name: barcode, type: string }
    belongsTo:
      - { name: category, entity: Categories }

  ItemUnits:
    properties:
      - { name: conversion_factor, type: number }
      - { name: is_base_unit, type: boolean }
    belongsTo:
      - { name: item, entity: Items }
      - { name: unit, entity: Units }

  ItemPrices:
    properties:
      - { name: buying_price, type: number }
      - { name: selling_price, type: number }
    belongsTo:
      - { name: item, entity: Items }
      - { name: unit, entity: Units }
```

When creating a new item we just send the payload with itemunits and itemprices then it should be able to create these relation entities:

```
{
      "id": 2,
      "name": "Onion",
      "barcode": "768876817",
      "itemunits": [
        {
          "id": 2,
          "conversion_factor": 1,
          "is_base_unit": true,
        }
      ],
      "itemprices": [
        {
          "id": 2,
          "buying_price": 20,
          "selling_price": 22,
        }
      ]
    }
```
