### DISCUSSION TITLE
:tada: Custom Endpoints are now live in Manifest! :rocket:

### DISCUSSION THREAD

**Discussion by SebConejo** [mnfst/llm-gateway#304] [Announcements]
Hello everyone! 

Following webhooks, this is the next step in letting you seamlessly add custom logic to your projects.

How easy is it? Have a look!

:one: Define your endpoint in manifest/backend.yml
```yaml
  endpoints:
    helloWorld:
      path: /hello-world
      method: GET
      handler: helloWorld
````

:two: Write your handler in manifest/handlers/helloWorld.js
```javascript
  export default async function helloWorld(req, res) {
    return res.json({ message: "Hello, world!" });
  }
````

:fire: Your custom `/hello-world` endpoint is ready.

:book: Check out the docs to get started: :point_right: https://manifest.build/docs/endpoints

🗳️ We've created a poll to better understand which language you'd prefer for custom endpoints in the future. 👉 https://github.com/mnfst/manifest/discussions/303
