### DISCUSSION TITLE
🔑 Ownership-based access is now available

### DISCUSSION THREAD

**Discussion by SebConejo** [mnfst/llm-gateway#448] [Announcements]
Hi folks,

We’ve just published a new release that adds ownership-based access for items. You can now use the `self` condition in your access rules to ensure that only an item’s owner is permitted to perform those actions.

```yml
Cat:
  properties:
    - name
  belongsTo:
    - User
  policies:
    create:
      - { access: restricted, allow: User, condition: "self" }
```
This makes it straightforward to lock down create, read, update, or delete operations so they only apply to the item’s owner.

📘 See the updated documentation: https://manifest.build/docs/access#ownership-based-access

🙏 Thanks to @tvanh3 for requesting this feature! Thanks to @signalwerk and @lollillol for upvoting it!

Happy coding 😃,
