### ISSUE TITLE
Create a demo TODO APP with React / NextJS / Svelte / Vue

### ISSUE THREAD

**Issue by brunobuddy** [mnfst/llm-gateway#206]
We built a [demo repo](https://github.com/mnfst/frontend-examples) to showcase the integration of Manifest with different frontend frameworks.

The demo is based on the popular [TodoMVC website](https://todomvc.com/) that compares the differents frameworks building the same **todo app**. In our use case we added a small Manifest backend with a db for persistant data:

```yaml
name: My TODO App ✅
entities:
  Todo:
    seedCount: 10
    properties:
      - title
      - { name: completed, type: boolean }
```

We need now to create frontend examples based on the TodoMVC ones:
- [ ] React
- [ ] NextJS
- [ ] Svelte
- [ ] Vue
- [ ] Other frontend ?

## How to submit a demo

- Clone the [mnfst/frontend-examples](https://github.com/mnfst/frontend-examples) repository
- Install and checkout the angular implementation for inspiration
- Go to [TodoMVC Github](https://github.com/tastejs/todomvc/tree/master/examples) and grab the framework that you are going to integrate
- Copy it on the `/examples` folder and connect it to the backend
- Make sure that there is an `npm run dev` script in the package.json
- Make your PR in the  [mnfst/frontend-examples](https://github.com/mnfst/frontend-examples) mentionning this issue
