### ISSUE TITLE
Relationships not found if emoji in entity name

### ISSUE THREAD

**Issue by brunobuddy** [mnfst/llm-gateway#236]
If we have an emoji in the entity name, there is an error at build as the validator does not recognize the name with an emoji.

Try to run manifest with that backend.yml:

```yaml
name: My pet app 🐾
entities:
  Owner 👩‍🦰:
    properties:
      - name
      - { name: birthdate, type: date }

  Cat 😺:
    properties:
      - name
      - { name: age, type: number }
      - { name: birthdate, type: date }
    belongsTo:
      - Owner
```
