### ISSUE TITLE
Failing if entity relation name is same as entity name 

### ISSUE THREAD

**Issue by brunobuddy** [mnfst/llm-gateway#257]
If the name of the entity is "Group" there is some weird behaviours: https://discord.com/channels/1089907785178812499/1323062280581152828/1323062280581152828

We should check that entity names do not overlap reserved words in SQLite to prevent those issues. Or find a workaround

**Comment by cosatsil** [comment]
To be clear, this is not about the name "Group". It is about any case in which a relationship with another entity is named the same as that entity (or the same but in plural form). For example, any of the following:
```
{ name: units, entity: Unit }
{ name: events, entity: Event }
{ name: bags, entity: Bag }
```
will trigger an error.

**Comment by brunobuddy** [comment]
Hello @cosatsil I am currently working on this issue but I could not reproduce it with my YAML:

```yaml
name: My pet app

entities:
  Group:
    mainProp: slug
    properties:
      - slug
      - name
    belongsToMany:
      - { name: units, entity: Unit }

  Unit:
    mainProp: slug
    properties:
      - slug
      - name

```
Can you send me yours ? The one that fails ?
