### ISSUE TITLE
Error when adding entity with property `id`

### ISSUE THREAD

**Issue by ryuujo1573** [mnfst/llm-gateway#378]
```
MissingPrimaryColumnError: Entity "VirtualTerminal" does not have a primary column. Primary column is required to have in all your entities. Use @PrimaryColumn decorator to add a primary column to your entity.
```

Reproduce: (enabled the property `id`)

```yml
entities:
  VirtualTerminal:
    seedCount: 5
    # mainProp: id
    properties:
      # - id
      - name
      - description
```

Simply put, is this an undocumented limitation or a bug?
