### ISSUE TITLE
Keep the original aspect ratio with image type

### ISSUE THREAD

**Issue by ronaldaug** [mnfst/llm-gateway#380]
I think when "width" and "height" values are omitted, the image should retain its original size and ratio. However, currently it crops every image to default sizes (80x80 for thumbnail and 160x160 for medium).

```
entities:
  Post:
    properties:
      - { name: photo, type: image }
```

I also discovered that changing to `type: file` prevents the image from being cropped, though it won't display as a thumbnail in the admin panel.

So, Is there a way to keep the original aspect ratio with image type?

**Comment by ronaldaug** [comment]
Found the solution: we can provide only the **width**

e.g:
```yaml
entities:
  Post:
    properties:
      - {
        name: photo,
        type: image,
        options:
          { sizes: { small: { width: 500 }, large: { width: 1000 } } }
      }
```

Or we can use `fit` option as `contain` or `fill` as explained in [the doc](https://manifest.build/docs/entities#image). 

```
entities:
  Post:
    properties:
      - {
        name: photo,
        type: image,
        options:
          { sizes: { small: { width: 500, fit: 'contain' }, large: { width: 1000, fit: 'contain' } } }
      }
```
